version: '3.9'

volumes:
  storage:

networks:
  internal:

services:
  database:
    image: postgres:14-alpine
    restart: always
    volumes:
      - storage:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - internal
    environment:
      - POSTGRES_DB=marombei
      - POSTGRES_USER=marombei
      - POSTGRES_PASSWORD=marombei

  cache:
    image: redis:7
    container_name: marombei_cache
    ports:
      - 6379:6379
    networks:
      - internal

  mail:
    image: mailhog/mailhog
    container_name: marombei
    ports:
      - "8025:8025"
    networks:
      - internal
